version: '3.8'

services:
  database:
    image: mysql:5.7
    volumes:
      - ./StoreManager.sql:/docker-entrypoint-initdb.d/StoreManager.sql
    ports:
      - 3307:3307
    environment:
      - MYSQL_ROOT_PASSWORD=test
  app:
    platform: linux/amd64
    image: node:latest
    container_name: container_api
    restart: always
    depends_on:
      - database
    volumes:
      - .:/app
    ports:
      - 3000:3000
    working_dir: /app
    command: bash -c "npm install & npm start"
